### PR TITLE
Impl Clone for FFI wrappers.

### PR DESCRIPTION
**Pull request by hghwng**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
I've published version `0.0.21` of `lldb-sys` which will be needed for this to compile.

Would you mind updating the version required as part of this commit so that it is all correct?

Also, if you have a moment and don't mind, could you move the `impl Clone` so that it is before the `impl Debug` / `impl fmt::Debug` so that they stay in roughly alphabetical order?  If not, no big deal as that's pretty boring and tedious.

**Comment by hghwng** [comment]
Thanks for the feedback! The details you mentioned are pretty helpful, and I'll fix them soon.

The fix (also the previous work in `lldb-sys`) is not that tedious — thanks to shell scripting and editor macros.

**Comment by hghwng** [comment]
What about this version?

**Comment by waywardmonkeys** [comment]
Looks great to me! Thanks!

**Pull request merged**
