### PR TITLE
add SBProcess and SBThread broadcaster bit definitions

### PR DESCRIPTION
**Pull request by roccoblues**
Taken from the public lldb API:

* `SBThread`: https://github.com/llvm/llvm-project/blob/60de56c743c414240b293a8b8ee10bc2129d7e10/lldb/include/lldb/API/SBThread.h#L29-L33
* `SBProcess`: https://github.com/llvm/llvm-project/blob/main/lldb/include/lldb/API/SBProcess.h#L32-L37

I need them to make sense of the events.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Looks like it needs an allow for the missing docs? (Or add some docs…)

**Comment by roccoblues** [comment]
> Looks like it needs an allow for the missing docs? (Or add some docs…)

yep, I hope the names speak for themselves since the original API also doesn't have docs.

Also had to rename them to make clippy happy.

**Review by waywardmonkeys — APPROVED** [review]

**Comment by waywardmonkeys** [comment]
Thank you! (I'd love to hear sometime (publicly or privately) what you're doing with this if you're open to saying.)

**Comment by roccoblues** [comment]
Thank you for merging!

> Thank you! (I'd love to hear sometime (publicly or privately) what you're doing with this if you're open to saying.)

Sure, I'm playing with the idea to create a native UI, with [egui](https://docs.rs/egui/latest/egui/), for `lldb`. Running, stepping, inspecting frames and variables already works. Here's a, slightly outdated, screenshot. The code isn't public anywhere yet, but happy to ping you once I have something more robust.

Screenshot 2024-04-17 at 15 22 17

**Pull request merged**
